# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
 
networks:
  test:
    name: fabric_test
 
services: 


  ca-orderer:
    image: hyperledger/fabric-ca:latest
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=9055
      - FABRIC_CA_SERVER_TLS_CERTFILE=tls/cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=tls/key.pem
      - FABRIC_CA_SERVER_CSR_CN=ca-orderer
      - FABRIC_CA_SERVER_CSR_HOSTS="*.orderer.com,ca.orderer.com"
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:19055
    ports:
      - "9055:9055"
      - "19055:19055"  
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' 
    volumes:  
      - ../organizations/fabric-ca/ca-orderer:/etc/hyperledger/fabric-ca-server
      - ../organizations/tlsca-orderer/rcaadmin/msp/keystore/key.pem:/etc/hyperledger/fabric-ca-server/tls/key.pem
      - ../organizations/tlsca-orderer/rcaadmin/msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/cert.pem
    container_name: ca-orderer 
    networks:  
      - test  
