# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
 
networks:
  test:
    name: fabric_test

services: 
  tlsca-tcs:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=tlsca-tcs
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' 
    volumes:  
      - ../organizations/fabric-ca/tlsca-tcs:/etc/hyperledger/fabric-ca-server
    container_name: tlsca-tcs
    networks: 
      - test

  ca-tcs:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-tcs
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7055
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17055
    ports:
      - "7055:7055"
      - "17055:17055"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d' 
    volumes:  
      - ../organizations/fabric-ca/ca-tcs:/etc/hyperledger/fabric-ca-server
      - ../organizations/tlsca-tcs/rcaadmin/msp/keystore/key.pem:/etc/hyperledger/fabric-ca-server/tls/key.pem
      - ../organizations/tlsca-tcs/rcaadmin/msp/signcerts/cert.pem:/etc/hyperledger/fabric-ca-server/tls/cert.pem
    container_name: ca-tcs
    networks: 
      - test
