# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
  - &Org3
    # DefaultOrg defines the organization which is used in the sampleconfig
    # of the fabric.git development environment
    Name: GOOGLE

    # ID to load the MSP definition as
    ID: GOOGLEMSP

    MSPDir: ../TWG/peerOrganizations/google.com/msp

    Policies:
      Readers:
        Type: Signature
        Rule: "OR('GOOGLEMSP.admin', 'GOOGLEMSP.peer', 'GOOGLEMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('GOOGLEMSP.admin', 'GOOGLEMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('GOOGLEMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('GOOGLEMSP.peer')"
